spring.application.name=ProyectoPracticas

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.format_sql=true

# Datos de conexión
spring.datasource.url=jdbc:mysql://localhost:3306/store
spring.datasource.username=root
spring.datasource.password=elorrieta

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Desactivar la recopilación de estadísticas de Hibernate
spring.jpa.properties.hibernate.generate_statistics=false
logging.level.org.springframework=DEBUG
logging.level.your.package=TRACE



