package storeHouse.Objects;
// Generated 10 mar 2025, 12:25:45 by Hibernate Tools 6.5.1.Final

/**
 * InvoiceDetails generated by hbm2java
 */
public class InvoiceDetails implements java.io.Serializable {

	private Integer detailId;
	private Products products;
	private Invoices invoices;
	private int quantity;
	private boolean paid;

	public InvoiceDetails() {
	}

	public InvoiceDetails(Products products, Invoices invoices, int quantity, boolean paid) {
		this.products = products;
		this.invoices = invoices;
		this.quantity = quantity;
		this.paid = paid;
	}

	public Integer getDetailId() {
		return this.detailId;
	}

	public void setDetailId(Integer detailId) {
		this.detailId = detailId;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Invoices getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Invoices invoices) {
		this.invoices = invoices;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public boolean isPaid() {
		return this.paid;
	}

	public void setPaid(boolean paid) {
		this.paid = paid;
	}

}
