package storeHouse.Objects;
// Generated 10 mar 2025, 12:25:45 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products")
public class Products implements java.io.Serializable {

	private int productId;
	private byte[] image;
	private String name;
	private Integer amount;
	private Integer productLimit;
	private Boolean season;
	private Boolean enabled;
	private Set invoiceDetailses = new HashSet(0);

	public Products() {
	}

	public Products(int productId) {
		this.productId = productId;
	}

	public Products(int productId, byte[] image, String name, Integer amount, Integer productLimit, Boolean season,
			Boolean enabled, Set invoiceDetailses) {
		this.productId = productId;
		this.image = image;
		this.name = name;
		this.amount = amount;
		this.productLimit = productLimit;
		this.season = season;
		this.enabled = enabled;
		this.invoiceDetailses = invoiceDetailses;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getProductLimit() {
		return this.productLimit;
	}

	public void setProductLimit(Integer productLimit) {
		this.productLimit = productLimit;
	}

	public Boolean getSeason() {
		return this.season;
	}

	public void setSeason(Boolean season) {
		this.season = season;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Set getInvoiceDetailses() {
		return this.invoiceDetailses;
	}

	public void setInvoiceDetailses(Set invoiceDetailses) {
		this.invoiceDetailses = invoiceDetailses;
	}

}