package storeHouse.Objects;
// Generated 10 mar 2025, 12:25:45 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private String name;
	private String mail;
	private byte[] image;
	private String pass;
	private boolean rol;
	private Set invoiceses = new HashSet(0);

	public Users() {
	}

	public Users(String name, String mail, String pass, boolean rol) {
		this.name = name;
		this.mail = mail;
		this.pass = pass;
		this.rol = rol;
	}

	public Users(String name, String mail, byte[] image, String pass, boolean rol, Set invoiceses) {
		this.name = name;
		this.mail = mail;
		this.image = image;
		this.pass = pass;
		this.rol = rol;
		this.invoiceses = invoiceses;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public boolean isRol() {
		return this.rol;
	}

	public void setRol(boolean rol) {
		this.rol = rol;
	}

	public Set getInvoiceses() {
		return this.invoiceses;
	}

	public void setInvoiceses(Set invoiceses) {
		this.invoiceses = invoiceses;
	}

}
